### PR TITLE
Redefinition of recursive_mutex

### PR DESCRIPTION
**Pull request by yuxuanchiadm**
When I compile engine with mingw-w64 i686, gcc 5.3.0. I got redefinition error of recursive_mutex. So I did this quick fix.

There are some open questions:

1. Why we need this monkey patch before. Does previous version of mingw mutex header doesn't define it?
2. Does this PR break anything? It looks fine. But synchronization and multithreading... Who knows?
3. Should we just delete this monkey patch because we probably don't need it anymore?
4. Anything else.

### CODE REVIEW

**Comment by McKay42** [comment]
You are using a strange outdated version of mingw-w64, try using the installer here (which is also linked in the engine readme and strongly suggested): https://sourceforge.net/projects/mingw-w64/

I can't compile it with mine (g++ 6.2.0) without the WinMinGW.Mutex.h file, could the compile flag '-std=c++11' impact this?

**Comment by yuxuanchiadm** [comment]
Since [recursive_mutex](http://en.cppreference.com/w/cpp/thread/recursive_mutex) is part of c++11 std. The newer version of mingw-w64 with gcc version that support c++11 doesn't supported it looks make make no sense. I'll download new version of mingw-w64 and test it later.

**Comment by McKay42** [comment]
It's very strange, could also be a compiler configuration or installation problem on my side. Will be interesting to see what happens if you use the new version via the installer

**Comment by yuxuanchiadm** [comment]
I will just done the following step:

- [x] Download and installed new version of mingw-w64 i686-6.3.0-posix-dwarf-rt_v5-rev1.
- [x] Set my env variable "MINGW_HOME" to "\path\to\dir\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32".
- [x] Make sure I got "%MINGW_HOME%\bin" on "PATH" env variable.
- [x] Restart eclipse and make sure env variable reloaded using ProcessExplorer.
- [x] Do "$ git reset --hard HEAD~1".
- [ ] Clean everything and recompile project see what happend.
- [ ] Check mutex include file see if we got recursive_mutex.
- [ ] Anything.

**Pull request closed without merging**
